# -*- coding: utf-8 -*-
"""SRTY3009_A1__HTTP_Request_Classification_Random_Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTsRvsVHyxri0bT2UY5Hjjeq7kVS2nm3

By Alicia Lancaster 1295404 and Temar Lewis 1286410
"""

# ============================================================
# Cell 1: Imports & Environment Check
# ============================================================
#
# This section installs and imports all required libraries for:
# • Data analysis and preprocessing
# • Machine learning model development
# • Data visualization and evaluation
#
# The environment check verifies that all dependencies are
# installed correctly before building the ML pipeline.
# ============================================================

# Install required libraries
!pip install scikit-learn pandas numpy matplotlib seaborn -q
!pip install adversarial-robustness-toolbox -q
!pip install imbalanced-learn -q

# ---------------------------
# Standard Library Imports
# ---------------------------

import pandas as pd                  # Data loading and manipulation
import numpy as np                   # Numerical operations
import matplotlib.pyplot as plt      # Data visualization
import seaborn as sns                # Enhanced visualizations
import time                          # Training time measurement
import warnings
from google.colab import files



warnings.filterwarnings('ignore')    #Keep output clean


# ---------------------------
# Scikit-learn Imports
# ---------------------------

# Random Forest selected for multi-class attack classification.
# This model performs well on cybersecurity datasets containing
# complex and non-linear attack patterns.

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    precision_score,
    recall_score,
    confusion_matrix,
    f1_score #how well the model balances precision and recall
)

import joblib
import sklearn
import matplotlib


# ============================================================
# Environment Verification
# ============================================================

print('=' * 55)
print('Environment Verification')
print('=' * 55)

print(f'Pandas Version:        {pd.__version__}')
print(f'NumPy Version:         {np.__version__}')
print(f'Scikit-learn Version:  {sklearn.__version__}')
print(f'Matplotlib Version:    {matplotlib.__version__}')
print(f'Seaborn Version:       {sns.__version__}')

print('=' * 55)
print('✅ All libraries loaded successfully')
print('✅ Environment ready for machine learning pipeline')
print('=' * 55)

# ============================================================
# Cell 2: Load Dataset
# ============================================================

from google.colab import files
import pandas as pd
import numpy as np


# ============================================================
# Upload Dataset
# ============================================================

#uploaded = files.upload()

#file_path = list(uploaded.keys())[0]

#print("Loaded file:", file_path)


# ============================================================
# Load Dataset
# ============================================================

df = pd.read_csv('/content/final_multiclass_http_attack_dataset_v2.csv')

print('\nDataset Preview:')

print(df.head())


# ============================================================
# Dataset Shape
# ============================================================

print('\nDataset Shape:')

print(f'{df.shape[0]:,} rows × {df.shape[1]} columns')


# ============================================================
# Column Name Cleanup
# ============================================================

df.columns = df.columns.str.strip()

print('\nColumn spaces stripped successfully')


# ============================================================
# Dataset Loaded Successfully
# ============================================================

print('\n✅ Dataset loaded successfully')

print('✅ Ready for exploration and analysis')

print('=' * 65)

# ============================================================
# Cell 3: Explore & Understand the Data
# ============================================================

print('=' * 65)
print('CELL 3: EXPLORE & UNDERSTAND THE DATA')
print('=' * 65)


# ============================================================
# Dataset Shape
# ============================================================

print('\nDataset Shape:')

print(f'{df.shape[0]:,} rows × {df.shape[1]} columns')


# ============================================================
# Strip Column Spaces
# ============================================================

df.columns = df.columns.str.strip()

print('\n✅ Column spaces stripped successfully')


# ============================================================
# Column Names
# ============================================================

print('\nColumn Names:')

for column in df.columns:
    print('-', column)


# ============================================================
# Label Identification
# ============================================================

print('\nTarget Label Column: attack_type')


# ============================================================
# Class Distribution
# ============================================================

print('\nAttack Type Distribution:')

print(
    df['attack_type']
    .value_counts()
)


# ============================================================
# Dataset Data Types
# ============================================================

print('\nDataset Data Types:')

print(df.dtypes)


# ============================================================
# Missing Values
# ============================================================

print('\nMissing Values Per Column:')

print(df.isnull().sum())


# ============================================================
# EDA Summary
# ============================================================

print('\n✅ Dataset exploration completed')

print('✅ Label column identified')

print('✅ Class distribution verified')

print('✅ Dataset ready for balance checking')

print('=' * 65)

# ============================================================
# Cell 4: Data Balance Check
# ============================================================

import matplotlib.pyplot as plt

print('=' * 65)
print('CELL 4: DATA BALANCE CHECK')
print('=' * 65)


# ============================================================
# Class Distribution
# ============================================================

class_counts = df['attack_type'].value_counts()

print('\nAttack Class Distribution:')

print(class_counts)


# ============================================================
# Chart 1: Linear Scale
# ============================================================

plt.figure(figsize=(10,5))

class_counts.plot(kind='barh')

plt.title('Attack Class Distribution - Linear Scale')

plt.xlabel('Count')

plt.ylabel('Attack Type')

plt.show()


# ============================================================
# Chart 2: Log Scale
# ============================================================

plt.figure(figsize=(10,5))

class_counts.plot(kind='barh', log=True)

plt.title('Attack Class Distribution - Log Scale')

plt.xlabel('Log Count')

plt.ylabel('Attack Type')

plt.show()


# ============================================================
# Balance Check Summary
# ============================================================

print('\nClass Balance Observation:')

print(
    'The dataset is moderately imbalanced. '
    'Normal and Other Anomalous contain the largest number of samples, '
    'while Command Injection has very few samples.'
)

print('\n✅ Class imbalance verified')

print('✅ Dataset ready for cleaning and preprocessing')

print('=' * 65)

# ============================================================
# Cell 5: Clean + Split + Balancing
# ============================================================

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import (
    LabelEncoder,
    StandardScaler
)

from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTE

print('=' * 65)
print('CELL 5: CLEAN + SPLIT + BALANCING')
print('=' * 65)


# ============================================================
# Machine Learning Features
# ============================================================

ml_features = [

    'request_length',
    'num_parameters',
    'has_sql_keywords',
    'has_xss_patterns',
    'has_path_traversal',
    'has_command_injection',
    'special_char_count',
    'encoded_char_count',
    'path_depth',
    'digit_count',
    'uppercase_count'

]

print("\nFEATURES KEPT")

for feature in ml_features:
    print(feature)

dropped_features = ['raw_request']

print("\nFEATURES DROPPED")

for feature in dropped_features:
    print(feature)
print("\nraw_request removed because it is raw text metadata and cannot be used directly by Random Forest")

# ============================================================
# Step 5: Clean the Data
# ============================================================

print('\nSTEP 5: DATA CLEANING')

rows_before = len(df)


# ------------------------------------------------------------
# 1 Strip Column Spaces
# ------------------------------------------------------------

df.columns = df.columns.str.strip()

print('\n✅ Column spaces stripped')


# ------------------------------------------------------------
# 2 Remove Duplicate Rows
# ------------------------------------------------------------

duplicate_count = df.duplicated().sum()

df.drop_duplicates(inplace=True)

print(f'✅ Duplicates removed: {duplicate_count}')


# ------------------------------------------------------------
# 3 Replace Infinity with NaN
# ------------------------------------------------------------

df.replace(
    [np.inf, -np.inf],
    np.nan,
    inplace=True
)

print('✅ Infinity values replaced with NaN')


# ------------------------------------------------------------
# 4 Convert Features to Numeric
# ------------------------------------------------------------

for col in ml_features:

    if col in df.columns:

        df[col] = pd.to_numeric(
            df[col],
            errors='coerce'
        )

print('✅ Non-numeric values converted to NaN')


# ------------------------------------------------------------
# 5 Remove Metadata Columns
# ------------------------------------------------------------

metadata_columns = [

    'raw_request'

]

df.drop(

    columns=metadata_columns,

    inplace=True,

    errors='ignore'

)

print('✅ Metadata columns removed')

print(metadata_columns)


# ------------------------------------------------------------
# 6 Preserve NaN for Imputation
# ------------------------------------------------------------

print('✅ NaN values preserved for imputation')


# ============================================================
# Cleaning Summary
# ============================================================

print('\nCLEANING SUMMARY')

print(f'Rows before cleaning: {rows_before:,}')

print(f'Rows after cleaning:  {len(df):,}')

print(f'Duplicates removed:   {duplicate_count:,}')

print('Infinity values converted: checked')

print(f'NaN remaining:        {df.isnull().sum().sum()}')

print('\nClasses still present:')

print(df['attack_type'].value_counts())


# ============================================================
# Feature Selection
# ============================================================

X = df[ml_features]

y = df['attack_type']


# ============================================================
# Encode Labels
# ============================================================

target_encoder = LabelEncoder()

y_encoded = target_encoder.fit_transform(y)


# ============================================================
# Step 6: Train/Test Split
# ============================================================

print('\n' + '=' * 65)
print('STEP 6: SPLIT • IMPUTE • BALANCE • SCALE')
print('=' * 65)

X_train, X_test, y_train, y_test = train_test_split(

    X,
    y_encoded,

    test_size=0.20,

    stratify=y_encoded,

    random_state=42

)

train_pct = (
    pd.Series(y_train)
    .value_counts(normalize=True)
    * 100
).round(2)

test_pct = (
    pd.Series(y_test)
    .value_counts(normalize=True)
    * 100
).round(2)

distribution_table = pd.DataFrame({

    'Train %': train_pct,

    'Test %': test_pct

})

print('\nTrain vs Test Class %')

print(distribution_table)


# ============================================================
# Split Verification
# ============================================================

print('\n' + '=' * 65)

print('TRAIN / TEST SPLIT RESULTS')

print('=' * 65)

print(f'\nX_train : {X_train.shape[0]:,} rows × {X_train.shape[1]} features')

print(f'X_test  : {X_test.shape[0]:,} rows × {X_test.shape[1]} features')

print(f'y_train : {len(y_train):,} labels')

print(f'y_test  : {len(y_test):,} labels')

print('\nIMPORTANT: X_test and y_test are LOCKED')

print('They are never modified during training.')


# ============================================================
# Imputation
# ============================================================

print('\n' + '=' * 65)

print('IMPUTATION RESULTS')

print('=' * 65)

imputer = SimpleImputer(
    strategy='median'
)

X_train = imputer.fit_transform(
    X_train
)

X_test = imputer.transform(
    X_test
)

print('\nNaN after imputation')

print(
    'Train:',
    np.isnan(X_train).sum()
)

print(
    'Test:',
    np.isnan(X_test).sum()
)

print('\n✅ Missing values successfully imputed')

print('✅ No NaN values remain')


# ============================================================
# SMOTE Balancing
# ============================================================

print('\n' + '=' * 65)

print('SMOTE – Synthetic Minority Oversampling Technique')

print('=' * 65)

y_train_before = y_train.copy()

print('\nTraining class distribution BEFORE SMOTE')

print(
    pd.Series(y_train_before)
    .value_counts()
)

smote = SMOTE(

    random_state=42,

    k_neighbors=1

)

X_train_bal, y_train_bal = smote.fit_resample(

    X_train,

    y_train

)

print('\nTraining class distribution AFTER SMOTE')

print(
    pd.Series(y_train_bal)
    .value_counts()
)

print('\nSMOTE SUMMARY')

print(
    f'Before : {len(y_train_before):,} training samples'
)

print(
    f'After  : {len(y_train_bal):,} training samples'
)

print(
    'New synthetic samples:',
    f'{len(y_train_bal)-len(y_train_before):,}'
)

print('\nTest set untouched')

print(f'X_test shape : {X_test.shape}')

print(f'NaN confirmed : {np.isnan(X_train_bal).sum()}')

print('\n✅ Dataset balanced using SMOTE')


# ============================================================
# Feature Scaling
# ============================================================

print('\n' + '=' * 65)

print('FEATURE SCALING')

print('=' * 65)

scaler = StandardScaler()

X_train_bal = scaler.fit_transform(
    X_train_bal
)

X_test = scaler.transform(
    X_test
)

print('\n✅ Dataset standardized successfully')

print('=' * 65)

start_time = time.time()

# training code

end_time = time.time()

print(
    f"Training time: {end_time-start_time:.2f} seconds"
)

# ============================================================
# CELL 6: VERIFY READY FOR A3 (BASELINE MODEL)
# ============================================================
import seaborn as sns
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

print('=' * 65)
print('CELL 6: VERIFY READY FOR A3')
print('=' * 65)

# ============================================================
# Final Dataset Shapes
# ============================================================

print('\nFinal Dataset Shapes')
print(f'X_train_bal Shape : {X_train_bal.shape}')
print(f'X_test Shape      : {X_test.shape}')
print(f'y_train_bal Shape : {y_train_bal.shape}')
print(f'y_test Shape      : {y_test.shape}')

# ============================================================
# NaN Verification
# ============================================================

print('\nNaN Verification')
print('X_train_bal NaN:', np.isnan(X_train_bal).sum())
print('X_test NaN :', np.isnan(X_test).sum())

# ============================================================
# Infinity Verification
# ============================================================

print('\nInfinity Verification')
print('X_train_bal Inf:', np.isinf(X_train_bal).sum())
print('X_test Inf :', np.isinf(X_test).sum())

# ============================================================
# Dataset Status
# ============================================================

print('\nDataset Status')
print('✅ No duplicate records')
print('✅ No missing values')
print('✅ No infinity values')
print('✅ Dataset balanced using SMOTE')
print('✅ Features standardized')
print('✅ Ready for machine learning model training')
print('✅ Ready for Assignment 3')
print('=' * 65)

# ============================================================
# TRAIN RANDOM FOREST MODEL
# ============================================================

# ============================================================
# GRID SEARCH + MODEL TRAINING
# ============================================================

from sklearn.model_selection import GridSearchCV

param_grid = {

    'n_estimators': [100, 200],

    'max_depth': [10, 20, None],

    'min_samples_split': [2, 5]

}

grid = GridSearchCV(

    estimator=RandomForestClassifier(
        random_state=42
    ),

    param_grid=param_grid,

    scoring='f1_weighted',

    cv=5,

    n_jobs=-1,

    verbose=1

)
print("\nTraining Random Forest with GridSearchCV...")
grid.fit(X_train_bal, y_train_bal)

print('\nBest Parameters Found:')
print(grid.best_params_)

print('\nBest Cross-Validated Weighted F1:')
print(f'{grid.best_score_:.4f}')

model = grid.best_estimator_

# ============================================================
# Generate Predictions
# ============================================================

y_pred = model.predict(X_test)

# ============================================================
# Performance Metrics
# ============================================================

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(
    y_test,
    y_pred,
    average='weighted'
)

recall = recall_score(
    y_test,
    y_pred,
    average='weighted'
)

macro_f1 = f1_score(
    y_test,
    y_pred,
    average='macro'
)

weighted_f1 = f1_score(
    y_test,
    y_pred,
    average='weighted'
)

# ============================================================
# Baseline Metrics
# ============================================================

print('\nFINE-TUNED RANDOM FOREST PERFORMANCE METRICS')
print('=' * 65)

print(f'Accuracy Score              : {accuracy:.4f}')
print(f'Precision Score             : {precision:.4f}')
print(f'Recall Score                : {recall:.4f}')
print(f'Macro F1 Score              : {macro_f1:.4f}')
print(f'Weighted Average F1 Score   : {weighted_f1:.4f}')

print('=' * 65)

# ============================================================
# Classification Report
# ============================================================

print('\nFINE-TUNED CLASSIFICATION REPORT')
print('=' * 65)

print(
    classification_report(
        y_test,
        y_pred,
        target_names=target_encoder.classes_,
        zero_division=0
    )
)

# ============================================================
# Confusion Matrix
# ============================================================

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(10, 7))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Greens',
    linewidths=0.5,
    linecolor='white',
    cbar=False,
    xticklabels=target_encoder.classes_,
    yticklabels=target_encoder.classes_,
    annot_kws={"size": 12}
)

plt.title(
    'Fine-Tuned Random Forest Confusion Matrix'
)


plt.xlabel('Predicted Class')
plt.ylabel('True Class')

plt.xticks(rotation=20, ha='right')
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

# ============================================================
# Feature Importance Analysis
# ============================================================

feature_importance = pd.Series(
    model.feature_importances_,
    index=ml_features
).sort_values(ascending=False)

# ============================================================
# Top 10 Feature Importance Chart
# ============================================================

top_features = feature_importance.head(10)

plt.figure(figsize=(10, 6))

top_features.sort_values().plot(
    kind='barh',
    color='teal'
)

plt.title('Top 10 Most Important Features')
plt.xlabel('Importance Score')
plt.ylabel('Feature')

plt.tight_layout()
plt.show()

# ============================================================
# Top Features
# ============================================================

print('\nTop 10 Most Important Features')
print('=' * 65)
print(top_features)

# ============================================================
# Evaluation Summary
# ============================================================

print('\n✅ Fine-tuned model evaluation completed')
print('✅ Classification report generated')
print('✅ Confusion matrix generated')
print('✅ Feature importance generated')
print('✅ Weighted Average F1 Score recorded')
print('=' * 65)

# ============================================================
# STEP 3: PREDICTION PIPELINE DEMO
# ============================================================

print('\n' + '=' * 65)
print('PREDICTION PIPELINE DEMO')
print('=' * 65)

# Change this value if you want different examples
np.random.seed(42)

examples_found = 0

for class_name in ['Normal', 'SQL Injection', 'Other Anomalous']:

    class_id = target_encoder.transform([class_name])[0]

    class_indices = np.where(y_test == class_id)[0]

    idx = np.random.choice(class_indices)

    prediction = model.predict(
        X_test[idx].reshape(1, -1)
    )[0]

    probabilities = model.predict_proba(
        X_test[idx].reshape(1, -1)
    )[0]

    confidence = np.max(probabilities)

    actual_label = target_encoder.inverse_transform(
        [y_test[idx]]
    )[0]

    predicted_label = target_encoder.inverse_transform(
        [prediction]
    )[0]

    print('\n' + '-' * 65)

    print(f'Example #{examples_found + 1}')
    print(f'Real Label      : {actual_label}')
    print(f'Predicted Label : {predicted_label}')
    print(f'Confidence      : {confidence:.4f}')

    if actual_label == predicted_label:
        print('Result          : ✅ Correct Prediction')
    else:
        print('Result          : ❌ Incorrect Prediction')

    examples_found += 1

print('\n' + '=' * 65)
print('Prediction pipeline demo completed')
print('=' * 65)

# ============================================================
# ZOO ADVERSARIAL EVALUATION
# ============================================================

from art.estimators.classification import SklearnClassifier
from art.attacks.evasion import ZooAttack

print("\n" + "=" * 65)
print("ZOO ADVERSARIAL EVALUATION")
print("=" * 65)

art_classifier = SklearnClassifier(model=model)

X_test_subset = X_test
y_test_subset = y_test

epsilons = [0.00, 0.01, 0.05, 0.10]

accuracy_results = []
f1_results = []

attack = ZooAttack(
    classifier=art_classifier,
    confidence=0.0,
    targeted=False,
    max_iter=10,
    nb_parallel=1
)

print("\nGenerating adversarial examples...")
X_zoo = attack.generate(X_test_subset)

for eps in epsilons:

    if eps == 0.00:
        X_adv = X_test_subset.copy()
    else:
        X_adv = (
            X_test_subset +
            eps * (X_zoo - X_test_subset)
        )

    y_pred_adv = model.predict(X_adv)

    acc = accuracy_score(
        y_test_subset,
        y_pred_adv
    )

    f1 = f1_score(
        y_test_subset,
        y_pred_adv,
        average='weighted'
    )

    accuracy_results.append(acc)
    f1_results.append(f1)

    print(
        f"Epsilon={eps:.2f} | "
        f"Accuracy={acc:.4f} | "
        f"Weighted F1={f1:.4f}"
    )

# ============================================================
# ATTACK RESULTS TABLE
# ============================================================

attack_results = pd.DataFrame({
    'Epsilon': epsilons,
    'Accuracy': accuracy_results,
    'Weighted F1': f1_results
})

print("\nATTACK RESULTS")
print("=" * 65)
print(attack_results)

# ============================================================
# ACCURACY VS EPSILON CHART
# ============================================================

plt.figure(figsize=(8,5))

plt.plot(
    epsilons,
    accuracy_results,
    marker='o'
)

plt.title('Accuracy vs Epsilon (ZOO Attack)')
plt.xlabel('Epsilon')
plt.ylabel('Accuracy')

plt.grid(True)

plt.show()

# ============================================================
# ADVERSARIAL TRAINING DEFENCE
# ============================================================

print("\nGenerating adversarial training data...")

TRAIN_SAMPLE_SIZE = 5000

X_train_small = X_train_bal[:TRAIN_SAMPLE_SIZE]
y_train_small = y_train_bal[:TRAIN_SAMPLE_SIZE]

X_zoo_train = attack.generate(X_train_small)

epsilon_train = 0.05

X_adv_train = (
    X_train_small +
    epsilon_train *
    (X_zoo_train - X_train_small)
)

X_train_defended = np.vstack([
    X_train_small,
    X_adv_train
])

y_train_defended = np.hstack([
    y_train_small,
    y_train_small
])

defended_model = RandomForestClassifier(
    **grid.best_params_,
    random_state=42,
    n_jobs=-1
)

defended_model.fit(
    X_train_defended,
    y_train_defended
)

# ============================================================
# DEFENCE EVALUATION
# ============================================================

print("\nEvaluating defence...")

epsilon_defence = 0.05

X_adv_test = (
    X_test_subset +
    epsilon_defence *
    (X_zoo - X_test_subset)
)

baseline_pred = model.predict(X_adv_test)

baseline_acc = accuracy_score(
    y_test_subset,
    baseline_pred
)

baseline_f1 = f1_score(
    y_test_subset,
    baseline_pred,
    average='weighted'
)

defended_pred = defended_model.predict(
    X_adv_test
)

defended_acc = accuracy_score(
    y_test_subset,
    defended_pred
)

defended_f1 = f1_score(
    y_test_subset,
    defended_pred,
    average='weighted'
)

comparison_table = pd.DataFrame({

    'Metric': [
        'Accuracy',
        'Weighted F1'
    ],

    'Before Defence': [
        baseline_acc,
        baseline_f1
    ],

    'After Defence': [
        defended_acc,
        defended_f1
    ]
})

print("\nBEFORE VS AFTER DEFENCE (EPSILON = 0.05)")
print("=" * 65)
print(comparison_table)

# ============================================================
# CELL 7: SAVE MODEL + PREPROCESSING OBJECTS
# ============================================================

MODEL_PATH = "HTTP_Request_RF_Model.pkl"
IMPUTER_PATH = "HTTP_Request_Imputer.pkl"
SCALER_PATH = "HTTP_Request_Scaler.pkl"

joblib.dump(model, MODEL_PATH)
joblib.dump(imputer, IMPUTER_PATH)
joblib.dump(scaler, SCALER_PATH)

print("✅ Model saved:", MODEL_PATH)
print("✅ Imputer saved:", IMPUTER_PATH)
print("✅ Scaler saved:", SCALER_PATH)

# Verify loading
loaded_model = joblib.load(MODEL_PATH)
loaded_imputer = joblib.load(IMPUTER_PATH)
loaded_scaler = joblib.load(SCALER_PATH)

print("✅ Objects loaded successfully")

# ============================================================
# CELL 8: PREDICTION PIPELINE
# ============================================================

def predict_http_request(raw_row_dict):

    # Build dataframe
    row_df = pd.DataFrame([raw_row_dict])

    # Add missing columns
    for col in ml_features:
        if col not in row_df.columns:
            row_df[col] = 0

    # Match original feature order
    row_df = row_df[ml_features]

    # Apply preprocessing
    row_imp = loaded_imputer.transform(row_df)
    row_scaled = loaded_scaler.transform(row_imp)

    # Predict
    prediction = loaded_model.predict(row_scaled)[0]

    # Probabilities
    probabilities = loaded_model.predict_proba(row_scaled)[0]

    confidence = np.max(probabilities)

    predicted_label = target_encoder.inverse_transform(
        [prediction]
    )[0]

    scores = pd.Series(
        probabilities,
        index=target_encoder.classes_
    ).sort_values(ascending=False)

    print("Prediction:", predicted_label)
    print(f"Confidence: {confidence:.2%}")

    print("\nTop Probabilities")
    print(scores.head(3))

    return predicted_label, scores